name: Build/release

on:
  workflow_dispatch:
    inputs:
      github_link:
        description: 'GitHub Link'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Clone project
        run: git clone ${{ github.event.inputs.github_link }} project

      - name: Install dependencies
        run: cd project/capacitor && pnpm install --frozen-lockfile

      - name: Setup JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Setup Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip -d $HOME/sdk
          echo "y" | $HOME/sdk/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Build the app
        run: cd project/capacitor && npm run build:android

      - name: Build Debug APK
        run: cd project/capacitor/android && ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug-apk
          path: project/capacitor/android/app/build/outputs/apk/debug/*.apk
